version: '3.9'

services:
  fast-api-service:
    build:
      context: .
      target: build-image
    image: fastapi_boilerplate:latest
    volumes:
      - "./logs:/code/logs"
    environment:
      AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
      AUTH0_API_AUDIENCE: "${AUTH0_API_AUDIENCE}"
      AUTH0_ISSUER: "${AUTH0_ISSUER}"
      AUTH0_ALGORITHMS: "${AUTH0_ALGORITHMS}"
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.fast-api-service.rule=Host(`fastapi.localhost`)
      - traefik.http.routers.fast-api-service.entrypoints=http
      - traefik.http.services.fast-api-service.loadbalancer.server.port=8000

networks:
  traefik:
    external: true